### ISSUE TITLE
stop spamming this

### ISSUE THREAD

**Issue by zaclittleberry** [AssaEmpireToken/Pancakeswap-bot-moreprofit#1]
This is garbage and being spammed in reddits. Knock it off

**Comment by AssaEmpireToken** [comment]
Where on Reddit? We arent on any subreddit 😳

**Comment by AssaEmpireToken** [comment]
We have our YT Channel but no official Reddit Account

**Comment by AssaEmpireToken** [comment]
Hey, I can tell you it's not one of our employees. On the subject of bots, I can only say that it is quite damaging to work with something like that. We will inform Reddit and ask Reddit for an immediate ban on their accounts. Unfortunately I can't do much more in the meantime, even if I would like to, because we are affected by it ourselves. I assume that one of our "opponents" or rather "companions" runs these bots, but I can't say for sure. Thank you for your tip and I hope you can rest soon 😖
